feat: import graphs, contract and namespace using id
wundergraph/terraform-provider-cosmo pull request #12
Opened 2024-12-22 21:35 UTC by JivusAyrus

2025-01-03 09:08 UTC, StarpTech requested changes

2025-01-03 09:08 UTC, StarpTech commented on internal/service/subgraph/resource_cosmo_subgraph.go
> -		subgraphs, apiError := r.client.GetSubgraphs(ctx, data.Namespace.ValueString())
Looks good but we should start add a few integration tests.

2025-01-08 09:18 UTC, JivusAyrus commented on internal/service/subgraph/resource_cosmo_subgraph.go
> -		subgraphs, apiError := r.client.GetSubgraphs(ctx, data.Namespace.ValueString())
We do have tests

2025-01-08 09:19 UTC, JivusAyrus commented on internal/service/subgraph/resource_cosmo_subgraph.go
> -		subgraphs, apiError := r.client.GetSubgraphs(ctx, data.Namespace.ValueString())
I will see if i can add tests for importing the graphs

2025-01-08 12:42 UTC, StarpTech commented on internal/service/subgraph/resource_cosmo_subgraph.go
> -		subgraphs, apiError := r.client.GetSubgraphs(ctx, data.Namespace.ValueString())
Thanks, other than that looks great.

2025-01-20 12:31 UTC, StarpTech approved these changes
LGTM

2025-01-20 14:16 UTC, merged